# Generated by Django 3.1.7 on 2021-02-26 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20210226_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlistitem',
            name='comment',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
