# Generated by Django 3.1.7 on 2021-02-26 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20210226_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlistitem',
            name='comment',
        ),
    ]
