# Generated by Django 3.1.7 on 2021-02-26 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_remove_watchlistitem_comment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='watchlistitem',
            unique_together={('listing', 'watcher')},
        ),
    ]
