# Generated by Django 3.1.7 on 2021-03-02 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_auto_20210302_0214'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='watchlistitem',
            options={'verbose_name_plural': 'Watchlist Items'},
        ),
    ]
