# Generated by Django 3.1.7 on 2021-03-02 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
