# Generated by Django 3.1.7 on 2021-03-02 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_auto_20210302_1810'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='image',
            new_name='image_url',
        ),
    ]
