# Generated by Django 3.1.7 on 2021-03-03 23:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0023_listing_wishlist_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='wishlist_items',
            field=models.ManyToManyField(blank=True, related_name='wishlist_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
