# Generated by Django 3.1.7 on 2021-03-03 23:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0024_auto_20210303_2327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='wishlist_items',
        ),
        migrations.AddField(
            model_name='listing',
            name='watchlist_items',
            field=models.ManyToManyField(blank=True, related_name='watchlist_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
