# Generated by Django 3.1.7 on 2021-03-03 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0025_auto_20210303_2332'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listing',
            options={'ordering': ['title']},
        ),
    ]
