# Generated by Django 3.1.7 on 2021-03-03 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0027_auto_20210303_2349'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listing',
            options={'ordering': ['timestamp']},
        ),
    ]
